import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/app/globals.css"
import type { ReactNode } from "react"
import { dir } from "i18next"
import { languages } from "@/i18n/settings"
import { Footer } from "@/components/footer"

const inter = Inter({ subsets: ["latin"] })

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = Readonly<{
  children: ReactNode
  params: Promise<{
    lng: string
  }>
}>

export default async function RootLayout({ children, params }: Props) {
  const { lng } = await params
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <section className="flex min-h-screen flex-col justify-between">
          {children}
          <Footer />
        </section>
      </body>
    </html>
  )
}
